name: Test and Deploy MERN App

on:
  push:
    branches:
      - main
  workflow_dispatch: # manually run karne ke liye

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Test SSH to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "echo '🎉 SSH Connected Successfully!'"

  deploy:
    runs-on: ubuntu-latest
    needs: test-ssh  # deploy sirf SSH test ke pass hone ke baad chalega
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            cd /var/www/MERN-Portfolio

            echo "👉 Pulling latest code from GitHub..."
            git reset --hard
            git pull origin main

            echo "👉 Installing backend dependencies..."
            cd backend
            npm install --production

            echo "👉 Restarting backend with PM2..."
            pm2 restart portfolio-backend || pm2 start app.js --name portfolio-backend
            cd ..

            echo "👉 Installing frontend dependencies & building..."
            cd frontend
            npm install
            npm run build
            cd ..

            echo "👉 Restarting Nginx..."
            sudo systemctl restart nginx

            echo "✅ Deployment Completed Successfully!"
          EOF
